### ISSUE TITLE
load_model failing with custom Keras model

### ISSUE THREAD

**Issue by ashispapu** [stratospark/food-101-mobile#1]
Hello,

A really great tutorial!

Just what I was looking for. When I am trying this with a custom Keras model,the load_model() seems to be failing. I have a custom model trained in Keras that I am trying to bundle it as an android app. 

model = load_model('my_weights_tensorflow.h5')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-26058d518424> in <module>()
----> 1 model = load_model('my_weights_tensorflow.h5')

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in load_model(filepath, custom_objects)
    138     model_config = f.attrs.get('model_config')
    139     if model_config is None:
--> 140         raise ValueError('No model found in config file.')
    141     model_config = json.loads(model_config.decode('utf-8'))
    142     model = model_from_config(model_config, custom_objects=custom_objects)

ValueError: No model found in config file.

I could load your model without any problem.

Any input would be of great assistance.

Thanks in advance!

**Comment by stratospark** [comment]
Hi @ashispapu 

When I saved my original model, I did `model.save('foo.hdf5')`, which saves both the actual model definition plus the weights into a single file.

It seems as if you have only saved the weights into `my_weights_tensorflow.h5`. What you could do is execute all the code that builds up your model layers, run `model.load_weights('my_weights_tensorflow.h5')`, then run `model.save('full_model.h5')`.

There is a good summary of this here: https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

Hope this helps!

**Comment by ashispapu** [comment]
Yes. Now it up and running! Thanks!
